// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetPal.Api.Data;

#nullable disable

namespace PetPal.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260910142732_PetBrainV2IntentAndMemory")]
    partial class PetBrainV2IntentAndMemory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PetPal.Api.Entities.AdventureRecap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<int>("EstimatedCredits")
                        .HasColumnType("integer");

                    b.Property<string>("ExperienceKey")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("ExperienceRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("PromptHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("PromptTemplateVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ProviderJobId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("RealizedCredits")
                        .HasColumnType("integer");

                    b.Property<string>("RecapSpecHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SpecVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceRunId");

                    b.HasIndex("RecapSpecHash")
                        .IsUnique();

                    b.HasIndex("ChildProfileId", "RequestedAt");

                    b.ToTable("AdventureRecaps");
                });

            modelBuilder.Entity("PetPal.Api.Entities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("PetPal.Api.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ParentGatePinHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PetPal.Api.Entities.Badge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DescriptionAz")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("TitleAz")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("PetPal.Api.Entities.BehaviorEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChildProfileId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ChildProfileId", "OccurredAt");

                    b.ToTable("BehaviorEvents");
                });

            modelBuilder.Entity("PetPal.Api.Entities.ChatTurn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlockedReason")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FromAi")
                        .HasColumnType("boolean");

                    b.Property<bool>("FromChild")
                        .HasColumnType("boolean");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.HasKey("Id");

                    b.HasIndex("ChildProfileId", "Sequence");

                    b.ToTable("ChatTurns");
                });

            modelBuilder.Entity("PetPal.Api.Entities.ChildBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.HasIndex("ChildProfileId", "BadgeId")
                        .IsUnique();

                    b.ToTable("ChildBadges");
                });

            modelBuilder.Entity("PetPal.Api.Entities.ChildMission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.HasIndex("ChildProfileId", "MissionId")
                        .IsUnique();

                    b.ToTable("ChildMissions");
                });

            modelBuilder.Entity("PetPal.Api.Entities.ChildProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<bool>("ArenaEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("ArenaFriendsOnly")
                        .HasColumnType("boolean");

                    b.Property<int>("ArenaRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(300);

                    b.Property<string>("AvatarKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("BedtimeEndHour")
                        .HasColumnType("integer");

                    b.Property<int>("BedtimeStartHour")
                        .HasColumnType("integer");

                    b.Property<int>("CareActionCount")
                        .HasColumnType("integer");

                    b.Property<bool>("ChatEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DailyGoalTarget")
                        .HasColumnType("integer");

                    b.Property<int>("DailyMinutesLimit")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("FriendCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<int>("Gems")
                        .HasColumnType("integer");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateOnly?>("LastActiveOn")
                        .HasColumnType("date");

                    b.Property<Guid>("ParentUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Personality")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PersonalityChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Stars")
                        .HasColumnType("integer");

                    b.Property<int>("StreakDays")
                        .HasColumnType("integer");

                    b.Property<string>("UnlockedGames")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UtcOffsetMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FriendCode")
                        .IsUnique();

                    b.HasIndex("ParentUserId");

                    b.ToTable("ChildProfiles");
                });

            modelBuilder.Entity("PetPal.Api.Entities.DailyGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnsweredCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("Completed")
                        .HasColumnType("integer");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("MinutesSpent")
                        .HasColumnType("integer");

                    b.Property<bool>("RewardGranted")
                        .HasColumnType("boolean");

                    b.Property<int>("Target")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChildProfileId", "Date")
                        .IsUnique();

                    b.ToTable("DailyGoals");
                });

            modelBuilder.Entity("PetPal.Api.Entities.DeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParentUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.HasKey("Id");

                    b.HasIndex("ChildProfileId");

                    b.HasIndex("ParentUserId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("DeviceTokens");
                });

            modelBuilder.Entity("PetPal.Api.Entities.Discovery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<int>("StarsEarned")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChildProfileId", "CreatedAt");

                    b.ToTable("Discoveries");
                });

            modelBuilder.Entity("PetPal.Api.Entities.Duel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("CreatorArenaRating")
                        .HasColumnType("integer");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FriendsOnly")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPractice")
                        .HasColumnType("boolean");

                    b.Property<int>("Skill")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TargetChildProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByChildProfileId");

                    b.HasIndex("TargetChildProfileId");

                    b.HasIndex("Status", "ExpiresAt", "CreatedAt");

                    b.ToTable("Duels");
                });

            modelBuilder.Entity("PetPal.Api.Entities.DuelAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ChosenIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("DuelEntryId")
                        .HasColumnType("uuid");

                    b.Property<int>("ElapsedMs")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("DuelEntryId", "QuestionId")
                        .IsUnique();

                    b.ToTable("DuelAnswers");
                });

            modelBuilder.Entity("PetPal.Api.Entities.DuelEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ArenaRatingAfter")
                        .HasColumnType("integer");

                    b.Property<int>("ArenaRatingBefore")
                        .HasColumnType("integer");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("DuelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ResultSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SpeedBonusStars")
                        .HasColumnType("integer");

                    b.Property<int>("StarsEarned")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalMilliseconds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChildProfileId", "StartedAt");

                    b.HasIndex("DuelId", "ChildProfileId")
                        .IsUnique();

                    b.ToTable("DuelEntries");
                });

            modelBuilder.Entity("PetPal.Api.Entities.DuelQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DuelId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<bool>("PracticeCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("PracticeElapsedMs")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("DuelId", "Order")
                        .IsUnique();

                    b.ToTable("DuelQuestions");
                });

            modelBuilder.Entity("PetPal.Api.Entities.ExperienceRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Assisted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Choices")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentNodeId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("CurrentStage")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<int>("DefinitionVersion")
                        .HasColumnType("integer");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("EndingKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("ExperienceType")
                        .HasColumnType("integer");

                    b.Property<int>("HintsUsed")
                        .HasColumnType("integer");

                    b.Property<int>("Mistakes")
                        .HasColumnType("integer");

                    b.Property<bool>("RewardApplied")
                        .HasColumnType("boolean");

                    b.Property<int>("ScorePercent")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StoryFlags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("ChildProfileId")
                        .IsUnique()
                        .HasDatabaseName("IX_ExperienceRuns_ChildProfileId_Active")
                        .HasFilter("\"Status\" = 0");

                    b.HasIndex("ChildProfileId", "StartedAt");

                    b.HasIndex("ChildProfileId", "TemplateKey", "Status");

                    b.ToTable("ExperienceRuns");
                });

            modelBuilder.Entity("PetPal.Api.Entities.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FriendChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestedByChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FriendChildProfileId");

                    b.HasIndex("ChildProfileId", "FriendChildProfileId")
                        .IsUnique();

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("PetPal.Api.Entities.GameResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("GameKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("StarsEarned")
                        .HasColumnType("integer");

                    b.Property<int>("XpEarned")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChildProfileId", "CreatedAt");

                    b.ToTable("GameResults");
                });

            modelBuilder.Entity("PetPal.Api.Entities.IssuedPuzzle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Assisted")
                        .HasColumnType("boolean");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("BlueprintKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("BlueprintVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentSignature")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExperienceRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("GeneratorVersion")
                        .HasColumnType("integer");

                    b.Property<int>("HintsUsed")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Mechanic")
                        .HasColumnType("integer");

                    b.Property<string>("PrivateSolution")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PublicPayload")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("SceneSpecHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Seed")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("SolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StageIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChildProfileId", "IssuedAt");

                    b.HasIndex("ExperienceRunId", "StageIndex")
                        .IsUnique();

                    b.ToTable("IssuedPuzzles");
                });

            modelBuilder.Entity("PetPal.Api.Entities.LearningSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSprint")
                        .HasColumnType("boolean");

                    b.Property<int>("Skill")
                        .HasColumnType("integer");

                    b.Property<int>("StarsEarned")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.Property<int>("XpEarned")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChildProfileId", "StartedAt");

                    b.ToTable("LearningSessions");
                });

            modelBuilder.Entity("PetPal.Api.Entities.Mission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("DescriptionAz")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("RewardGems")
                        .HasColumnType("integer");

                    b.Property<int>("RewardStars")
                        .HasColumnType("integer");

                    b.Property<int?>("Skill")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Target")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("TitleAz")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorldZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("WorldZoneId");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("PetPal.Api.Entities.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Bond")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("Cleanliness")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Energy")
                        .HasColumnType("integer");

                    b.Property<string>("EquippedAccessories")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Fullness")
                        .HasColumnType("integer");

                    b.Property<int>("Happiness")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("HatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastDecayAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSleptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("UnlockedAccessories")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Xp")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChildProfileId")
                        .IsUnique();

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("PetPal.Api.Entities.PetIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpectedEndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OutcomeKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("PlannerVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ReasonKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("RelatedMemoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelatedMissionKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("SeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChildProfileId", "Status", "StartedAt");

                    b.ToTable("PetIntents");
                });

            modelBuilder.Entity("PetPal.Api.Entities.PetMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FactKey")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("Importance")
                        .HasColumnType("integer");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SupportCount")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<string>("ValueKey")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("ChildProfileId", "CreatedAt");

                    b.HasIndex("ChildProfileId", "Kind", "FactKey", "ValueKey")
                        .IsUnique();

                    b.ToTable("PetMemories");
                });

            modelBuilder.Entity("PetPal.Api.Entities.PlayerTrait", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("LastObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastStrongEvidenceAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ObservationCount")
                        .HasColumnType("integer");

                    b.Property<int>("PositiveEvidence")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("SkipEvidence")
                        .HasColumnType("integer");

                    b.Property<int>("SourceMask")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChildProfileId", "Category", "Key")
                        .IsUnique();

                    b.ToTable("PlayerTraits");
                });

            modelBuilder.Entity("PetPal.Api.Entities.PuzzleIllustration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("BlueprintKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("PromptHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("PromptTemplateVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SceneSpecHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SceneSpecHash")
                        .IsUnique();

                    b.ToTable("PuzzleIllustrations");
                });

            modelBuilder.Entity("PetPal.Api.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CorrectIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Hint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int>("MaxAge")
                        .HasColumnType("integer");

                    b.Property<int>("MinAge")
                        .HasColumnType("integer");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int>("Skill")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LanguageCode", "Skill", "Difficulty", "IsActive");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("PetPal.Api.Entities.RecommendationDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CandidateKeys")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContextHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<int>("Feedback")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FeedbackAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FitScore")
                        .HasColumnType("integer");

                    b.Property<int>("NoveltyScore")
                        .HasColumnType("integer");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer");

                    b.Property<string>("SelectedTemplateKey")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("SurpriseScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChildProfileId", "CreatedAt");

                    b.ToTable("RecommendationDecisions");
                });

            modelBuilder.Entity("PetPal.Api.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("PetPal.Api.Entities.RewardEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("ChildProfileId", "CreatedAt");

                    b.ToTable("RewardEntries");
                });

            modelBuilder.Entity("PetPal.Api.Entities.RunStageOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EffectKeys")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ExperienceRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("HintsUsed")
                        .HasColumnType("integer");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.Property<string>("SelectedOptionKeys")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StageOrdinal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceRunId", "NodeId")
                        .IsUnique();

                    b.HasIndex("ExperienceRunId", "StageOrdinal");

                    b.ToTable("RunStageOutcomes");
                });

            modelBuilder.Entity("PetPal.Api.Entities.SessionAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ChosenIndex")
                        .HasColumnType("integer");

                    b.Property<int>("ElapsedMs")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LearningSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("LearningSessionId", "QuestionId")
                        .IsUnique();

                    b.ToTable("SessionAnswers");
                });

            modelBuilder.Entity("PetPal.Api.Entities.SkillMastery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnsweredCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("Skill")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChildProfileId", "Skill")
                        .IsUnique();

                    b.ToTable("SkillMasteries");
                });

            modelBuilder.Entity("PetPal.Api.Entities.TeamMission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("DescriptionAz")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<int>("RewardStars")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Target")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("TitleAz")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("TeamMissions");
                });

            modelBuilder.Entity("PetPal.Api.Entities.TeamMissionMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("Contribution")
                        .HasColumnType("integer");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamMissionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChildProfileId");

                    b.HasIndex("TeamMissionId", "ChildProfileId")
                        .IsUnique();

                    b.ToTable("TeamMissionMembers");
                });

            modelBuilder.Entity("PetPal.Api.Entities.TraitDailyGain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("DayKey")
                        .HasColumnType("integer");

                    b.Property<int>("Gained")
                        .HasColumnType("integer");

                    b.Property<string>("TraitKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChildProfileId", "Category", "TraitKey", "DayKey")
                        .IsUnique();

                    b.ToTable("TraitDailyGains");
                });

            modelBuilder.Entity("PetPal.Api.Entities.WorldZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("DescriptionAz")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("NameAz")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("RequiredStars")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("WorldZones");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("PetPal.Api.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("PetPal.Api.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("PetPal.Api.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("PetPal.Api.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetPal.Api.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("PetPal.Api.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetPal.Api.Entities.AdventureRecap", b =>
                {
                    b.HasOne("PetPal.Api.Entities.ChildProfile", "ChildProfile")
                        .WithMany()
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildProfile");
                });

            modelBuilder.Entity("PetPal.Api.Entities.BehaviorEvent", b =>
                {
                    b.HasOne("PetPal.Api.Entities.ChildProfile", "ChildProfile")
                        .WithMany("BehaviorEvents")
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildProfile");
                });

            modelBuilder.Entity("PetPal.Api.Entities.ChatTurn", b =>
                {
                    b.HasOne("PetPal.Api.Entities.ChildProfile", "ChildProfile")
                        .WithMany("ChatTurns")
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildProfile");
                });

            modelBuilder.Entity("PetPal.Api.Entities.ChildBadge", b =>
                {
                    b.HasOne("PetPal.Api.Entities.Badge", "Badge")
                        .WithMany("ChildBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetPal.Api.Entities.ChildProfile", "ChildProfile")
                        .WithMany("Badges")
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("ChildProfile");
                });

            modelBuilder.Entity("PetPal.Api.Entities.ChildMission", b =>
                {
                    b.HasOne("PetPal.Api.Entities.ChildProfile", "ChildProfile")
                        .WithMany("Missions")
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetPal.Api.Entities.Mission", "Mission")
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildProfile");

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("PetPal.Api.Entities.ChildProfile", b =>
                {
                    b.HasOne("PetPal.Api.Entities.ApplicationUser", "ParentUser")
                        .WithMany("Children")
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentUser");
                });

            modelBuilder.Entity("PetPal.Api.Entities.DailyGoal", b =>
                {
                    b.HasOne("PetPal.Api.Entities.ChildProfile", "ChildProfile")
                        .WithMany("DailyGoals")
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildProfile");
                });

            modelBuilder.Entity("PetPal.Api.Entities.DeviceToken", b =>
                {
                    b.HasOne("PetPal.Api.Entities.ChildProfile", "ChildProfile")
                        .WithMany()
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PetPal.Api.Entities.ApplicationUser", "ParentUser")
                        .WithMany()
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ChildProfile");

                    b.Navigation("ParentUser");
                });

            modelBuilder.Entity("PetPal.Api.Entities.Discovery", b =>
                {
                    b.HasOne("PetPal.Api.Entities.ChildProfile", "ChildProfile")
                        .WithMany("Discoveries")
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildProfile");
                });

            modelBuilder.Entity("PetPal.Api.Entities.Duel", b =>
                {
                    b.HasOne("PetPal.Api.Entities.ChildProfile", "CreatedByChildProfile")
                        .WithMany()
                        .HasForeignKey("CreatedByChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetPal.Api.Entities.ChildProfile", "TargetChildProfile")
                        .WithMany()
                        .HasForeignKey("TargetChildProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByChildProfile");

                    b.Navigation("TargetChildProfile");
                });

            modelBuilder.Entity("PetPal.Api.Entities.DuelAnswer", b =>
                {
                    b.HasOne("PetPal.Api.Entities.DuelEntry", "DuelEntry")
                        .WithMany("Answers")
                        .HasForeignKey("DuelEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetPal.Api.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DuelEntry");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("PetPal.Api.Entities.DuelEntry", b =>
                {
                    b.HasOne("PetPal.Api.Entities.ChildProfile", "ChildProfile")
                        .WithMany("DuelEntries")
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetPal.Api.Entities.Duel", "Duel")
                        .WithMany("Entries")
                        .HasForeignKey("DuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildProfile");

                    b.Navigation("Duel");
                });

            modelBuilder.Entity("PetPal.Api.Entities.DuelQuestion", b =>
                {
                    b.HasOne("PetPal.Api.Entities.Duel", "Duel")
                        .WithMany("Questions")
                        .HasForeignKey("DuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetPal.Api.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Duel");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("PetPal.Api.Entities.ExperienceRun", b =>
                {
                    b.HasOne("PetPal.Api.Entities.ChildProfile", "ChildProfile")
                        .WithMany("ExperienceRuns")
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildProfile");
                });

            modelBuilder.Entity("PetPal.Api.Entities.Friendship", b =>
                {
                    b.HasOne("PetPal.Api.Entities.ChildProfile", "ChildProfile")
                        .WithMany()
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetPal.Api.Entities.ChildProfile", "FriendChildProfile")
                        .WithMany()
                        .HasForeignKey("FriendChildProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildProfile");

                    b.Navigation("FriendChildProfile");
                });

            modelBuilder.Entity("PetPal.Api.Entities.GameResult", b =>
                {
                    b.HasOne("PetPal.Api.Entities.ChildProfile", "ChildProfile")
                        .WithMany()
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildProfile");
                });

            modelBuilder.Entity("PetPal.Api.Entities.IssuedPuzzle", b =>
                {
                    b.HasOne("PetPal.Api.Entities.ChildProfile", "ChildProfile")
                        .WithMany()
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetPal.Api.Entities.ExperienceRun", "ExperienceRun")
                        .WithMany("Puzzles")
                        .HasForeignKey("ExperienceRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildProfile");

                    b.Navigation("ExperienceRun");
                });

            modelBuilder.Entity("PetPal.Api.Entities.LearningSession", b =>
                {
                    b.HasOne("PetPal.Api.Entities.ChildProfile", "ChildProfile")
                        .WithMany("Sessions")
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildProfile");
                });

            modelBuilder.Entity("PetPal.Api.Entities.Mission", b =>
                {
                    b.HasOne("PetPal.Api.Entities.WorldZone", "WorldZone")
                        .WithMany("Missions")
                        .HasForeignKey("WorldZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorldZone");
                });

            modelBuilder.Entity("PetPal.Api.Entities.Pet", b =>
                {
                    b.HasOne("PetPal.Api.Entities.ChildProfile", "ChildProfile")
                        .WithOne("Pet")
                        .HasForeignKey("PetPal.Api.Entities.Pet", "ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildProfile");
                });

            modelBuilder.Entity("PetPal.Api.Entities.PetIntent", b =>
                {
                    b.HasOne("PetPal.Api.Entities.ChildProfile", "ChildProfile")
                        .WithMany()
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildProfile");
                });

            modelBuilder.Entity("PetPal.Api.Entities.PetMemory", b =>
                {
                    b.HasOne("PetPal.Api.Entities.ChildProfile", "ChildProfile")
                        .WithMany("Memories")
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildProfile");
                });

            modelBuilder.Entity("PetPal.Api.Entities.PlayerTrait", b =>
                {
                    b.HasOne("PetPal.Api.Entities.ChildProfile", "ChildProfile")
                        .WithMany("Traits")
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildProfile");
                });

            modelBuilder.Entity("PetPal.Api.Entities.RecommendationDecision", b =>
                {
                    b.HasOne("PetPal.Api.Entities.ChildProfile", "ChildProfile")
                        .WithMany()
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildProfile");
                });

            modelBuilder.Entity("PetPal.Api.Entities.RefreshToken", b =>
                {
                    b.HasOne("PetPal.Api.Entities.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetPal.Api.Entities.RewardEntry", b =>
                {
                    b.HasOne("PetPal.Api.Entities.ChildProfile", "ChildProfile")
                        .WithMany("Rewards")
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildProfile");
                });

            modelBuilder.Entity("PetPal.Api.Entities.RunStageOutcome", b =>
                {
                    b.HasOne("PetPal.Api.Entities.ExperienceRun", "ExperienceRun")
                        .WithMany("StageOutcomes")
                        .HasForeignKey("ExperienceRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExperienceRun");
                });

            modelBuilder.Entity("PetPal.Api.Entities.SessionAnswer", b =>
                {
                    b.HasOne("PetPal.Api.Entities.LearningSession", "LearningSession")
                        .WithMany("Answers")
                        .HasForeignKey("LearningSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetPal.Api.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LearningSession");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("PetPal.Api.Entities.SkillMastery", b =>
                {
                    b.HasOne("PetPal.Api.Entities.ChildProfile", "ChildProfile")
                        .WithMany("SkillMasteries")
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildProfile");
                });

            modelBuilder.Entity("PetPal.Api.Entities.TeamMissionMember", b =>
                {
                    b.HasOne("PetPal.Api.Entities.ChildProfile", "ChildProfile")
                        .WithMany()
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetPal.Api.Entities.TeamMission", "TeamMission")
                        .WithMany("Members")
                        .HasForeignKey("TeamMissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildProfile");

                    b.Navigation("TeamMission");
                });

            modelBuilder.Entity("PetPal.Api.Entities.TraitDailyGain", b =>
                {
                    b.HasOne("PetPal.Api.Entities.ChildProfile", "ChildProfile")
                        .WithMany()
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildProfile");
                });

            modelBuilder.Entity("PetPal.Api.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("PetPal.Api.Entities.Badge", b =>
                {
                    b.Navigation("ChildBadges");
                });

            modelBuilder.Entity("PetPal.Api.Entities.ChildProfile", b =>
                {
                    b.Navigation("Badges");

                    b.Navigation("BehaviorEvents");

                    b.Navigation("ChatTurns");

                    b.Navigation("DailyGoals");

                    b.Navigation("Discoveries");

                    b.Navigation("DuelEntries");

                    b.Navigation("ExperienceRuns");

                    b.Navigation("Memories");

                    b.Navigation("Missions");

                    b.Navigation("Pet");

                    b.Navigation("Rewards");

                    b.Navigation("Sessions");

                    b.Navigation("SkillMasteries");

                    b.Navigation("Traits");
                });

            modelBuilder.Entity("PetPal.Api.Entities.Duel", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("PetPal.Api.Entities.DuelEntry", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("PetPal.Api.Entities.ExperienceRun", b =>
                {
                    b.Navigation("Puzzles");

                    b.Navigation("StageOutcomes");
                });

            modelBuilder.Entity("PetPal.Api.Entities.LearningSession", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("PetPal.Api.Entities.TeamMission", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("PetPal.Api.Entities.WorldZone", b =>
                {
                    b.Navigation("Missions");
                });
#pragma warning restore 612, 618
        }
    }
}
